spring.application.name=AUTH-SERVICE
server.port=8081
spring.config.import=optional:configserver:http://localhost:8888
spring.datasource.url=jdbc:mysql://localhost:3306/hms_auth_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{X-Correlation-Id}] %-5level %logger - %msg%n