spring.application.name=api-gateway
server.port=9092
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
management.endpoint.gateway.enabled=true
logging.level.org.springframework.cloud.gateway=DEBUG
management.endpoints.web.exposure.include=*

